"""empty message

Revision ID: 51a680b84c9e
Revises: d0c61b715be7
Create Date: 2026-06-16 20:37:26.084135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51a680b84c9e'
down_revision: Union[str, Sequence[str], None] = 'd0c61b715be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.create_foreign_key("fk_lesson_course_id", 'course', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_constraint("fk_lesson_course_id", type_='foreignkey')

    # ### end Alembic commands ###
